# -*- coding: utf-8 -*-
"""final projact - transformer - data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfnR9R0-2emfpORihX-YXcBkZIPe6dU6
"""

import gdown
import zipfile
import os

# יצירת תיקייה לנתונים (אם לא קיימת)
os.makedirs("/content/datasets", exist_ok=True)

# מזהה הקובץ מתוך הדרייב
file_id = "11bjXBQT4j54wGRCCPTjH0ZbNk0U7i6GE"
output = "/content/datasets/datasets.zip"

# הורדת הקובץ מה-Drive
gdown.download(f"https://drive.google.com/uc?id={file_id}", output, quiet=False)

# חילוץ הקבצים מתוך ה-ZIP
with zipfile.ZipFile(output, 'r') as zip_ref:
    zip_ref.extractall("/content/datasets")

# בדיקה אילו קבצים נפרקו
print("תוכן התיקייה לאחר החילוץ:")
!ls /content/datasets

import zipfile
import os

zip_files = [
    "/content/datasets/sentiment_tweets3.csv.zip",
    "/content/datasets/Suicide_Detection.csv.zip",
    "/content/datasets/depression_dataset_reddit_cleaned.csv.zip"
]

for file in zip_files:
    with zipfile.ZipFile(file, 'r') as zip_ref:
        zip_ref.extractall("/content/datasets")

import pandas as pd
df3 = pd.read_csv("/content/datasets/Combined Data.csv")
df4 = pd.read_csv("/content/datasets/depression_dataset_reddit_cleaned.csv")
df1 = pd.read_csv("/content/datasets/sentiment_tweets3.csv")
df2 = pd.read_csv("/content/datasets/Suicide_Detection.csv")